version: "3.5"
services:
  passportapi:
    build:
      context: ~/Загрузки/IdeaProjects/PassportApi
      dockerfile: Dockerfile
    container_name: passportapi
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
  postgres:
    image: postgres:14.3-alpine
    container_name: postgresdb
    ports:
      - "54333:5432"
    environment:
      POSTGRES_DB: "passportapi1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "PassworD1"
      PG_DATA: ./snap/postgres/data/pgdata
    #        volumes:
    #          - "./Загрузки/IdeaProjects/PassportApi/src/main/resources/iniema.sql"
    #    - "./docs/sql/conf.d:/etc/mysql/conf.d"t.db.sql"
    #    #          - "./Загрузки/IdeaProjects/PassportApi/src/main/resources/sch
    #    - "./docs/sql/mysql-files.d:/var/lib/mysql-files"
    #    - "./scp-persistence/src/main/resources/db/migration:/var/lib/mysql-files/migration"


