mysql:
  image: b2261d3c6ce0
  container_name: modest_tereshkova
#  volumes:
#    - "./docs/sql/initdb.d:/docker-entrypoint-initdb.d"
#    - "./docs/sql/conf.d:/etc/mysql/conf.d"
#    - "./docs/sql/mysql-files.d:/var/lib/mysql-files"
#    - "./scp-persistence/src/main/resources/db/migration:/var/lib/mysql-files/migration"
  ports:
    - "5433:5433"
  environment:
    POSTGRES_ROOT_PASSWORD: PassworD1