version: "3.5"
services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgresdb
    ports:
      - "5432:5432"
    #      - "54333:5432"
    environment:
      POSTGRES_DB: "passportapi1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "PassworD1"
      PG_DATA: ./snap/postgres/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d passportapi1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  passportapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: passportapi
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
  #    restart: always
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresdb:5432/passportapi1"
